version: "3"
services:
    flask:
        image: flask_test
        build:
            context: ./flask
            dockerfile: Dockerfile
        container_name: flask_test
        volumes:
            - ./flask/app:/usr/src/app
        secrets:
            - secrets_test
        env_file: 
            - ./.env
        networks:
            - internal
        # gunicorn -w WORKERS -b BIND $(MODULE_NAME):$(VARIABLE_NAME) --reload
        command: /usr/local/bin/gunicorn -c /usr/src/gunicorn.conf.py -w 2 -b 0.0.0.0:8000 app:app --timeout 60 --reload
    nginx:
        image: nginx_test
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx_test
        ports:
            - "${NGINX_PORT}:80"
        networks:
            - internal
secrets:
    secrets_test:
        file: ./secrets/secrets_test
networks:
    internal:
        driver: bridge